import './globals.scss'
import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import MainProvider from 'providers/MainProvider'

export const metadata: Metadata = {
	title: 'Create Next App',
	description: 'Generated by create next app',
}

export default function RootLayout({
	children,
}: {
	children: React.ReactNode
}) {
	return (
		<html lang="en">
			<body>
				<MainProvider>{children}</MainProvider>
			</body>
		</html>
	)
}
